name: CI BUILD

on:
  push:
    branches-ignore: [ "pages" ]
  pull_request:
    branches-ignore: [ "pages" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: install Python3
      run: sudo apt install python3 

    - name: build
      run: ./build.sh

    - name: check root dir
      run: ls -la

    - name: check iso_root
      run: ls -la iso_root

    - name: check bin
      run: ls -la bin
