name: CI BUILD

on:
  push:
    branches-ignore: [ "pages" ]
  pull_request:
    branches-ignore: [ "pages" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: install depends
      run: sudo apt install clang-format python3 git gdisk gcc g++ xorriso make mtools curl
    
    - name: install limine
      run: |
        git clone https://github.com/limine-bootloader/limine.git --branch=v5.x-branch-binary --depth=1

    - name: build
      run: chmod +x build.sh && ./build.sh

    - name: check root dir
      run: ls -la

    - name: check iso_root
      run: ls -la iso_root

    - name: check bin
      run: ls -la bin
