name: Release Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Configure Git user
        run: |
          git config --global user.email "github@github.com"
          git config --global user.name "Build bot"

      - name: Build
        run: |
          python3 build.py
          git config advice.addIgnoredFile false

      - name: Add and commit files
        uses: EndBug/add-and-commit@v9
        with:
          add: 'kernel.elf mseos.hdd mseos.iso'
          author_name: Bot
          author_email: bot@example.com
          commit: --signoff
          message: Update
          new_branch: binary
          pathspec_error_handling: ignore
          push: true
          github_token: ${{ secrets.GITHUB_TOKEN }}